### ISSUE TITLE
Fix inline LaTeX

### ISSUE THREAD

**Issue by ransonhobbes** [the-dao/whitepaper#4]

**Comment by glauseWilde** [comment]
Weird workaround but I can post the images here and then reference them in the main paper. Haha

![r](https://user-images.githubusercontent.com/49164280/63477963-8d58ce00-c43c-11e9-9bfe-db43a0308659.png)
 ![a](https://user-images.githubusercontent.com/49164280/63477966-9184eb80-c43c-11e9-8951-b141642e96b3.png) Bonding Curve Starting Price
![c](https://user-images.githubusercontent.com/49164280/63477969-93e74580-c43c-11e9-9355-d4844dba0fe3.png)  = 1.0053611  (Growth Factor)
![phi](https://user-images.githubusercontent.com/49164280/63477971-96e23600-c43c-11e9-8d74-6ed5557d771d.png)
![tokenRatio](https://user-images.githubusercontent.com/49164280/63477974-98abf980-c43c-11e9-97e1-2826469ea288.png) or 1.6180339887
 - Converts Tokens into degrees

**Comment by glauseWilde** [comment]
![burn-price](https://user-images.githubusercontent.com/49164280/63478191-aca42b00-c43d-11e9-8f5f-d7928b8d4b73.png)
![Liquidity](https://user-images.githubusercontent.com/49164280/63478193-ad3cc180-c43d-11e9-883a-401fdc5bc798.png)

**Comment by glauseWilde** [comment]
Changes merged
